class Find_selectors:
    value_placeholder_search = 'Ищете конкретный фильм, сериал или актера?'
    value_no_result_search = 'Результатов по данному запросу нет'
    value_label_search = 'Поле глобального поиска на странице'
    value_all_result_search = 'Все результаты поиска'
    input_global_search = '//input[@id="global_page-search"]'
    input_search_with_placeholder = '//input[@id="global_page-search" and @placeholder="' + value_placeholder_search + '"]'
    magnifier_in_global_search = '//button[@class="input__global-search-button h-hidden--text"]'
    input_global_search_with_value = '//input[@id="global_page-search" and @value="{}"]'
    result_search_drop_down_list = '//h4[@class="suggest__resul-title" and text()="{}"]'
    not_result_search = '//span[@class="suggest__info-text" and text()="' + value_no_result_search + '"]'
    label_search = '//label[@for="global_page-search" and text()="' + value_label_search + '"]'
    all_result_search_in_input_search = '//a[@class="suggest__footer-link" and text()="' + value_all_result_search + '"]'
    first_result_search_in_input_search = '//ul[@class="suggest__result"]/li[1]'
